name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Show server hostname
        run: hostname

      - name: Check Docker containers
        run: docker ps

      - name: Restart Docker containers
        run: |
          cd C:\Users\Administrator\Desktop\Config_system\V3\Reporting_Module_v0.1\Reporting_Module_v0.1
          docker compose up -d
